name: pdf-delivery
on: [push]
jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repo
        uses: actions/checkout@v3
      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Thesis.tex
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: Thesis.pdf
